### ISSUE TITLE
Support Fixed length extraction

### ISSUE THREAD

**Issue by ph** [elastic/dissect-specification#6]
Take the following string`A0118`, The `A` represents the message class, the `01` is the month and `18` is the day. In the current dissect syntax there is no way to define fixed length keys, theses extraction should be O(n).

Suggested syntax:

```
`%{foobar*N} 
```

where **N** is a positive number for the number of chars to extract for the key.

**Comment by ycombinator** [comment]
Hi @ph @jakelandis It looks like a community user is trying to address this enhancement via https://github.com/elastic/beats/pull/17191. I'm not familiar with this repo so I have a couple of questions:

1. I imagine it's okay to implement this enhancement in the Beats `dissect` processor even if it isn't also implemented in the Logstash and Ingest Node ones. That is, I assume it's okay to proceed with reviewing and accepting the community contribution PR I linked to above?

2. (Assuming the answer to 1. is yes) If/when https://github.com/elastic/beats/pull/17191 is merged, do we also want a PR to this repo here, updating the README with the relevant syntax enhancements?

3. Finally, I assume we want to leave this issue here open even after https://github.com/elastic/beats/pull/17191 is merged?

**Comment by ph** [comment]
@ycombinator thanks for the ping on that, @vjsamuel did message me for that because the PR is created from a colleague at eBay and I had an early previous of the diff, I believe what you are proposing is OK, accept that PR get it merged and update the documentation in this repository to reflect the change and keep the issue open on this repository until all implementation is done.

@jakelandis  and @jsvd can you take the lead to create the issues for the implementation in Elasticsearch and Logstash?

**Comment by ph** [comment]
Looking at the [tests](https://github.com/elastic/beats/pull/17191/files#diff-c35940a3b4877fa00006fb2815a2afc1) I think its safe addition to our syntax.

**Comment by jakelandis** [comment]
ES issue logged: https://github.com/elastic/elasticsearch/issues/55273
